Development branch
mosesmuchemi/anibaba-muchemi-youtube-clone pull request #1
Opened 2019-08-21 19:39 UTC by mosesmuchemi

Requesting a code review for the embedding images and video project.

2019-08-22 00:02 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-22 00:27 UTC, Torres-ssf requested changes
### Great work team :clap: 
Nice job on this project. But before merging to master we need to make some changes to make your project even better.

[REQUIRED]
- [x] The search bar must be aligned to the middle of the navbar

[REQUIRED]
- [x] The video description section must have a 'share' button.

[REQUIRED]
- [x] The video description section must show the avatar of the user who uploaded the video

[REQUIRED]
- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

[REQUIRED]
- [x] Since this project is an assignment is a good practice to include in the readme file the assignment link and also the GitHub account from the contributors. If you need a guide you can check this [one](https://github.com/Torres-ssf/apple-site-clone/blob/master/README.md)

[FRIENDLY-REMAINDER]
As it's said on the pathwrite, you should use GitHubFlow: For HTML & CSS projects. So for the next project try to give a feature name for the branch. :smile: 

Please make these changes and submit for code review again :+1: 
Happy conding :computer:

2019-08-22 00:27 UTC, Torres-ssf commented on index.html
> +    <div class="navbar">
[OPTIONAL]
Using the `nav` tag for the navbar make your HTML code more semantic. This is a very important topic. You can learn more about [here](http://seekbrevity.com/semantic-markup-important-web-design/).

2019-08-22 00:27 UTC, Torres-ssf commented on index.html
> +    <div class="videobox">
[OPTIONAL]
It's also a good practice to use the `main` tag for the most relevant content of your page.

2019-08-22 20:06 UTC, Oghenebrume50 requested changes
Hi team, good job so far, we have made good progress. 
There seems to be an issue with the page layout though, the upnext sections show below the video and not to the side as it should

The readme file is not propely written please see recommendation from the previous reviewer, did you read that :thinking:

2019-08-22 20:11 UTC, Oghenebrume50 requested changes
Fix these things and submit for re-review :pray:

2019-08-22 20:11 UTC, Oghenebrume50 commented on index.html
> +        <div class="search-container" style="padding-left: 350px">
Inline styles are generally frowned upon, please move all inline styles to the css file

2019-08-22 20:11 UTC, Oghenebrume50 commented on youtubestyle.css
> +  /*float: right;*/
Please delete all commented codes

2019-08-30 00:35 UTC, Ispirett commented
#Reviewing

2019-08-30 00:43 UTC, Ispirett approved these changes
Hey!!!!!!!!!! Folks great job implementing changes :1st_place_medal: :100:  please make changes below and then you can complete this project.

#### Git/Githubflow reminder.

Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

2019-08-30 00:43 UTC, Ispirett commented on index.html
> +                <span id="shareButton">50,446 views</span>
You have duplicated  **ids**  please use a class instead

2019-08-30 05:46 UTC, merged